language: cpp
compiler: gcc

env:
jobs:
  addons:
    apt:
      packages:
        - zlib1g-dev
  include:
  #   - name: "Ubuntu 14"
  #     dist: trusty
  #     addons:
  #       apt:
  #         packages:
  #           - libhdf5-dev
  #     script: autoreconf && ./configure && make && make test
  #   - name: "Ubuntu 16 hdf5 install script"
  #     dist: xenial
  #     addons:
  #       apt:
  #         packages:
  #           - valgrind
  #     script:
  #       - autoreconf && ./scripts/install-hdf5.sh 2> /dev/null && ./configure --enable-localhdf5 && make && make test
  #       - valgrind --leak-check=full --error-exitcode=1 ./slow5tools f2s test/data/raw/chr22_meth_example-subset-multi > /dev/null
  #   - name: "Ubuntu 16 pure make"
  #     os: linux
  #     dist: xenial
  #     script: make && make test
  #   - name: "OSX"
  #     os: osx
  #     addons:
  #       homebrew:
  #         packages:
  #           - hdf5
  #         update: false
  #     script: autoreconf && ./configure && make && make test
  #   - name: "OSX pure make"
  #     os: osx
  #     script: make && make test
    - name: "arm64"
      arch: arm64
      os: linux
      addons:
        apt:
          packages:
            - zlib1g-dev
            - libhdf5-dev
      script: autoreconf && ./configure && make && make test
    - name: "arm64-zstd"
      arch: arm64
      os: linux
      addons:
        apt:
          packages:
            - zlib1g-dev
            - libhdf5-dev
            - libzstd1-dev
      script: autoreconf && ./configure && make zstd=1 && export zstd=1 && make test
    # - name: "arm64 hdf5 install script"
    #   arch: arm64
    #   os: linux
    #   addons:
    #     apt:
    #       packages:
    #         - zlib1g-dev
    #   script: autoreconf && ./scripts/install-hdf5.sh 2> /dev/null && ./configure --enable-localhdf5 && make && make test
    - name: "IBM Power CPUs"
      arch: ppc64le
      os: linux
      addons:
        apt:
          packages:
            - zlib1g-dev
            - libhdf5-dev
      script: autoreconf && ./configure && make && make test
    # - name: "IBM Z CPUs"
    #   arch: s390x
    #   os: linux
    #   addons:
    #     apt:
    #       packages:
    #         - zlib1g-dev
    #         - libhdf5-dev
    #   script: autoreconf && ./configure && make && make test
    # - stage: deploy
    #   name: "GitHub Release"
    #   dist: trusty
    #   script:
    #     - make dist
    #     - mkdir -p slow5tools-${TRAVIS_TAG}
    #     - make && mv slow5tools slow5tools-${TRAVIS_TAG}/slow5tools_x86_64_linux
    #     - cp -r README.md LICENSE docs slow5tools-${TRAVIS_TAG}/
    #     - tar -zcf slow5tools-${TRAVIS_TAG}-binaries.tar.gz slow5tools-${TRAVIS_TAG}
    #     - rm -rf slow5tools-${TRAVIS_TAG}
    #   deploy:
    #     provider: releases
    #     api_key:
    #       secure: KT3XFGJDQaN4EIbjRqAxnNFcG3fpkSFKct32bupVdlTMbzoI2c9oPyYKmUESyJODZML2BAwKV1knXrzhU/8o+vEDmTFdQ5fRNNHP8kcx6RVIZMSsJ+rF2DDl7sitr0rndyPbT97ACbsSZSdRiWK8MKo6YeMUJNkhuBOjXISFl4uiNezK0HeFCepQdWwB8W7De/1kgNQa9ZL6O7deiB+6DDZOVF/jr/YvIxCjytGwhFW6E5/EDHVmTt+9aXRXVgffzq9Ltt5oS30uYfWNJfAsk+81XEnuZ7GUGSyN4N77Xk2cI1LD3E8m1kMHksd34tn0A97nT4CPPI+WoUootzLDh29fUmSDPXbqwCGFDk8FTVUSAuwxZQQAESJrFv9fVl1vWTh3Bj8NkzXAHgmTtaBCxeIUhN+pBX3d7QQMYGpUHGGdIENGpfVi9vnnAYSsYs1foJtfuhw534ejju4laZ0bXVUE0w5AAKEw8H1xA+lS413ugKwAXEX6naFAD6NkZaX3ISSVeewIqtIW6UFCNqt/U++OY9vcwzFDbUq/wEjZtNRLzXzHzaObomRsOKqldje3FxH9p1QIPZXWgLBx8FhdFG6P+Nilhifq7Dcgx1dybKGTWOOurXrPKVgC9bLtXe/49LVMk5TirYtj2gXmlofi1SD52T9HpZVWH9haJ+Rnjso=
    #     file_glob: true
    #     file: slow5tools-*.tar.gz
    #     skip_cleanup: true
    #     on:
    #       branch: master
    #       repo: hasindu2008/slow5
    #       tags: true
    #   before_deploy:
    #     - make clean
